### ISSUE TITLE
neovim lsp integration possible

### ISSUE THREAD

**Issue by DoktorMike** [nikeee/dot-language-server#3]
Awesome language server! I use DOT all the time. Thanks for this. Any idea how hard/easy it would be to add this language server to neovim?

**Comment by nikeee** [comment]
I don't use neovim. But basically, all what you need is an LSP Client. There seems to be one:
https://github.com/neovim/nvim-lspconfig
It looks like the thing in "Custom Configuration" is what you need.
After [installing the language server](https://github.com/nikeee/dot-language-server#installation), you need to configure the LSP plugin accordingly. Maybe you can evaluate the sample for the Sublime Text configuration in the README.md for that.

**Comment by DoktorMike** [comment]
I've added a PR to neovim now here for your reference: https://github.com/neovim/nvim-lspconfig/pull/792 should go in soon.

**Comment by mjlbach** [comment]
This can be closed :)
