### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by mkohlhaas** [nikeee/dot-language-server#54]
Just a quick newbie question. Is there a `formatter` for dot files?

**Comment by mkohlhaas** [comment]
Could [Prettier](https://github.com/ts-graphviz/prettier-plugin-dot?tab=readme-ov-file) be incorporated into the language server?

**Comment by nikeee** [comment]
There is none. Incorporating prettier would be a huge effort. We're open for contributions, though.

**Comment by mkohlhaas** [comment]
Okay. Fair enough.

I'm not into JavaScript/Typescript. 😢
